# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/posit-dev/air-pre-commit
    # Air version
    rev: 0.9.0
    hooks:
      # Run the formatter
      - id: air-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.0
    hooks:
      - id: typos
  # - repo: https://github.com/lorenzwalthert/precommit
  #   rev: v0.4.3.9021
  #   hooks:
  #     # codemeta must be above use-tidy-description when both are used
  #     # -   id: codemeta-description-updated
  #     - id: use-tidy-description
  #     - id: lintr
  #     - id: parsable-R
  #     - id: no-browser-statement
  #     - id: no-debug-statement
  #     - id: deps-in-desc
  #       exclude: docker/.*|renv/.*
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: end-of-file-fixer
        exclude: '\.Rd'
ci:
  autofix_prs: true # set to false if we don't want fixes automatically applied by ci
  autoupdate_schedule: quarterly
