# additional packages from suggests lists
# and/or for the Docker image

library(AnnotationHub)
library(BSgenome)
library(celldex)
library(ComplexHeatmap)
library(eds)
library(eisaR)
library(ensembldb)
library(ggforce)
library(GenomicFeatures)
library(kableExtra)
library(ontoProc)
library(optparse)
library(rmarkdown)
library(scater)
library(scran)
library(SingleR)
library(tidyverse)
