# Build a the docker image
name: Build scpca-tools image

on:
  push:
    branches:
      - main
      - master
      - jashapiro/33-automate-docker-builds
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alexslemonade/scpca-tools

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value={{date 'YYYY-MM-DD'}}
            type=semver,pattern={{raw}}
            type=edge,branch=main

      - uses: docker/build-push-action@v2
        with:
          context: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

