# Build a the docker image
name: Build scpca-tools image

on:
  push:
    branches:
      - main
      - master
      - jashapiro/33-automate-docker-builds

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scpca-tools

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=schedule,pattern={{date 'YYYY-MM-DD'}}

      - run: echo "${{ steps.meta.outputs.tags }}"

