name: Build scpca-tools image

on:
  push:
    branches:
      - main
      - jashapiro/actions-update
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alexslemonade/scpca-tools

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{raw}}
            type=edge,branch=main

      - uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker"
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

